### ISSUE TITLE
Dienste stoppen 

### ISSUE THREAD

**Issue by Krocko** [lkn94/RaspberryBackup#1]
Hallo Lukas. 
Ich habe die ursprüngliche Anleitung auf raspberrypi.tips gelesen. Dort ist geschrieben, das man diverse Dienste vor dem Backup stoppen sollte. Ist das bei deinem Script nicht erforderlich?

**Comment by lkn94** [comment]
Hallo Krocko,

es ist im Grunde immer besser die Dienste zu stoppen, da es sonst zu einer Inkonsistenz kommen kann. Bislang habe ich allerdings keinerlei Probleme gehabt und lasse meine Dienste immer im laufenden Betrieb sichern.

Falls du andere Erfahrungen gemacht hast, würde ich mich aber über dein Feedback sehr freuen.
