### ISSUE TITLE
Konsolenmeldung nach Ausführung des Skripts

### ISSUE THREAD

**Issue by tobschndr** [lkn94/RaspberryBackup#2]
Ich bekomme diese Meldung nachdem das Skript ausgeführt wurde:

> rm: missing operand
> Try 'rm --help' for more information.

**Comment by lkn94** [comment]
Wie viele Backups hast du schon machen lassen? Sofern es weniger als die angegebene Menge im Skript sind kann es sein, dass eine leere Menge an den Befehl rm übergeben werden. Daher erhältst du die Fehlermeldung.

**Comment by tobschndr** [comment]
Danke Dir für Deine schnelle Rückmeldung. Daran kann es vermutlich liegen. Durch die Spielerei mit dem Skript war mein Ordner mit den Backups zwischenzeitlich wieder leer. Somit kann die Meldung igorniert werden - und der Issue geschlossen :)
