### ISSUE TITLE
Fehler am Ende der Script ausführung

### ISSUE THREAD

**Issue by Peter1980FFM** [lkn94/RaspberryBackup#5]
Hallo Bekomme am ende der Scriptausführung folgenden fehler
/mnt/nas/Backup_RASPIS/Deconz /home/pi
rm: fehlender Operand
„rm --help“ liefert weitere Informationen.
/home/pi
Wenn ich das jetzt hinter rm mit -f ergänze habe ich diese Fehlermeldung nicht mehr ggf muss die Anleitung angepasst werden?

**Comment by lkn94** [comment]
Hallo Peter,

sorry für die späte Rückmeldung. Bei Fragen ist es immer besser, sich bei mir im Blog zu melden. Dort kann ich erheblich früher reagieren.
Das kann passieren, wenn du noch keine 5 Sicherungen (Variable BACKUP_ANZAHL) erreicht hast und ist nicht weiter bedenklich. Den Fehler kannst du ignorieren. Er verschwindet, sobald du die Anzahl der Backups erreicht hast.
